use std::env;
use std::fs;
use std::path::{Path, PathBuf};

// Preserve the product-facing order from the original registry. New skill
// directories that are not listed here are still discovered and appended in
// lexical order, so this is presentation metadata rather than a resource list.
const PREFERRED_SKILL_ORDER: &[&str] = &[
    "visual-explanations",
    "office-document-design",
    "docx-document-design",
    "pptx-presentation-design",
    "xlsx-workbook-design",
    "evidence-first",
    "doc-script-editor",
    "skill-creator",
    "fiction-writing",
    "speechwriting",
    "research-synthesis",
    "editorial-revision",
    "persona-design",
];

fn sorted_entries(dir: &Path) -> Vec<PathBuf> {
    let mut entries = fs::read_dir(dir)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", dir.display()))
        .map(|entry| entry.expect("failed to read skill asset entry").path())
        .collect::<Vec<_>>();
    entries.sort();
    entries
}

fn collect_files(dir: &Path, files: &mut Vec<PathBuf>) {
    for path in sorted_entries(dir) {
        if path.file_name().and_then(|name| name.to_str()) == Some("__pycache__")
            || path.extension().and_then(|extension| extension.to_str()) == Some("pyc")
        {
            continue;
        }
        let metadata = fs::symlink_metadata(&path)
            .unwrap_or_else(|error| panic!("failed to inspect {}: {error}", path.display()));
        if metadata.file_type().is_symlink() {
            panic!(
                "built-in skill assets may not contain symlinks: {}",
                path.display()
            );
        }
        if metadata.is_dir() {
            collect_files(&path, files);
        } else if metadata.is_file() {
            files.push(path);
        }
    }
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

fn skill_slug(path: &Path) -> &str {
    path.file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("")
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let skills_root = manifest_dir.join("assets").join("skills");
    println!("cargo:rerun-if-changed={}", skills_root.display());

    let mut skill_dirs = sorted_entries(&skills_root)
        .into_iter()
        .filter(|path| path.is_dir() && path.join("SKILL.md").is_file())
        .collect::<Vec<_>>();
    skill_dirs.sort_by(|left, right| {
        let rank = |path: &PathBuf| {
            PREFERRED_SKILL_ORDER
                .iter()
                .position(|candidate| *candidate == skill_slug(path))
                .unwrap_or(usize::MAX)
        };
        rank(left)
            .cmp(&rank(right))
            .then_with(|| skill_slug(left).cmp(skill_slug(right)))
    });

    let mut generated = String::from(
        "// @generated by build.rs from assets/skills. Do not edit by hand.\n\
         static BUILTIN_SKILLS: &[BuiltinSkillBundle] = &[\n",
    );

    for skill_dir in skill_dirs {
        let slug = skill_dir
            .file_name()
            .and_then(|name| name.to_str())
            .expect("built-in skill directory names must be UTF-8");
        let skill_md = skill_dir.join("SKILL.md");
        fs::read_to_string(&skill_md)
            .unwrap_or_else(|error| panic!("{} must be UTF-8: {error}", skill_md.display()));

        let mut files = Vec::new();
        collect_files(&skill_dir, &mut files);
        files.retain(|path| path != &skill_md);
        files.sort();

        generated.push_str("    BuiltinSkillBundle {\n");
        generated.push_str(&format!("        slug: {},\n", rust_string(slug)));
        generated.push_str(&format!(
            "        skill_md: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {})),\n",
            rust_string(&format!("/assets/skills/{slug}/SKILL.md"))
        ));
        generated.push_str("        resources: &[\n");

        for file in files {
            fs::read_to_string(&file)
                .unwrap_or_else(|error| panic!("{} must be UTF-8: {error}", file.display()));
            let relative = file
                .strip_prefix(&skill_dir)
                .expect("skill resource must stay inside its skill directory")
                .to_string_lossy()
                .replace('\\', "/");
            generated.push_str("            BuiltinSkillResource {\n");
            generated.push_str(&format!(
                "                path: {},\n",
                rust_string(&relative)
            ));
            generated.push_str(&format!(
                "                content: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {})),\n",
                rust_string(&format!("/assets/skills/{slug}/{relative}"))
            ));
            generated.push_str("            },\n");
        }

        generated.push_str("        ],\n");
        generated.push_str("    },\n");
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("builtin_skills.rs"), generated)
        .expect("failed to write generated built-in skill registry");
}
