import type { CompanionSettings } from '../../types/conversation';

export const DEFAULT_COMPANION_SETTINGS: CompanionSettings = {
  enabled: false,
  selectedPetId: null,
  displayMode: 'always',
  interactionMode: 'smart',
  showInChat: true,
  autoShowOnStart: false,
  continueWhenMainHidden: true,
  scale: 1,
  animationFpsCap: 24,
  reducedMotion: false,
  idleActions: true,
  autoWalk: false,
  showBubbles: true,
  bubbleTaskTitles: false,
  privacyMode: true,
  successHoldMs: 4_000,
  failureHoldMs: 6_000,
  alwaysOnTop: true,
  visibleOnAllWorkspaces: false,
  lockPosition: false,
  activeRunPolicy: 'highest_priority',
  pinnedRunId: null,
  pinnedProjectId: null,
  monitorId: null,
  anchor: 'bottom_right',
  position: null,
  edgeSnap: true,
  avoidTaskbar: true,
  allowMonitorMove: true,
  codexImportPath: null,
};
